repos:
  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3  
    hooks:
      - id: isort
        language_version: python3

  # You can add other hooks here as needed
